// Oisin Gibson - L00172671
// Test file for App component

// Import testing utilities from React Testing Library
import { render, screen } from '@testing-library/react';
// Import the App component to test
import App from './App';

/**
 * Test: Renders learn react link
 * Verifies that the App component renders a link with the text "learn react"
 * 
 * This is a default test generated by Create React App.
 * In a production app, this should be updated to test actual app functionality.
 */
test('renders learn react link', () => {
  // Render the App component in a test environment
  render(<App />);
  // Query the DOM for an element containing "learn react" (case-insensitive)
  const linkElement = screen.getByText(/learn react/i);
  // Assert that the element exists in the document
  expect(linkElement).toBeInTheDocument();
});
